name: kostock
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  google_sign_in: ^5.1.0
  cloud_firestore: ^5.0.2
  http: ^1.2.1
  cupertino_icons: ^1.0.6

dependency_overrides:
  firebase_core_platform_interface: 5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1  # 아이콘 생성기 추가
  flutter_lints: ^4.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon_img.png"  # 변경할 아이콘 경로

flutter:
  assets:
    - assets/logo.png
    - assets/signup_logo.png
    - assets/news_image.png
    - assets/news_image_1.png
    - assets/news_image_2.png
    - assets/news_image_3.png
  uses-material-design: true
